language: php
sudo: required
services:
  - docker

matrix:
  include:
    - php: '7.3'
before_install:
  - cd docker/mpd
  - docker pull vitiman/alpine-mpd
  - docker-compose up -d
  - cd ../..
install:
  - composer install

script:
  - ./vendor/bin/phpunit

after_script:
  - cd docker/mpd
  - docker logs mpd
